### ISSUE TITLE
Error when trying to add android platform

### ISSUE THREAD

**Issue by megalepozy** [felquis/ionic-cca#1]
Hey felquis,

I'm getting the following result & error when I run ./node_modules/.bin/cca platform add android :
cca v0.4.3
Creating android project...
Creating Cordova project for the Android platform:
    Path: platforms/android
    Package: com.your.company.projectname
    Name: projectname
    Android target: android-19
Copying template files...
Project successfully created.
Running command: /home/nimrod/PhpstormProjects/ionic-cca/hooks/before_prepare/cca-pre-prepare.js /home/nimrod/PhpstormProjects/ionic-cca

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1001:11)
    at Process.ChildProcess._handle.onexit (child_process.js:792:34)
Error: Hook failed with error code 8: /home/nimrod/PhpstormProjects/ionic-cca/hooks/before_prepare/cca-pre-prepare.js
    at /home/nimrod/PhpstormProjects/ionic-cca/node_modules/cca/node_modules/cordova-lib/src/hooks/HooksRunner.js:194:23
    at _rejected (/home/nimrod/PhpstormProjects/ionic-cca/node_modules/cca/node_modules/cordova-lib/node_modules/q/q.js:797:24)
    at /home/nimrod/PhpstormProjects/ionic-cca/node_modules/cca/node_modules/cordova-lib/node_modules/q/q.js:823:30
    at Promise.when (/home/nimrod/PhpstormProjects/ionic-cca/node_modules/cca/node_modules/cordova-lib/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/home/nimrod/PhpstormProjects/ionic-cca/node_modules/cca/node_modules/cordova-lib/node_modules/q/q.js:741:41)
    at /home/nimrod/PhpstormProjects/ionic-cca/node_modules/cca/node_modules/cordova-lib/node_modules/q/q.js:557:44
    at flush (/home/nimrod/PhpstormProjects/ionic-cca/node_modules/cca/node_modules/cordova-lib/node_modules/q/q.js:108:17)
    at process._tickCallback (node.js:419:13)

I got the same error when I try 'cca run android --device' after I answer Y (which btw doesn't create the file created-with-cca-version)

Honestly I'm so limited in time that I decided to just play safe and go for Phonegap with Ionic without cca or Crosswalk, maybe I'll add them to the project later on.

And one last note, I'm programming at the web for 13 years now, never in my life I saw someone try to help someone else (which he doesn't know) as much as u did to me, so really, thanks a lot!!!

Nimrod

**Comment by megalepozy** [comment]
oh one last note in case u want to keep working on this reposirtoy, I ran 'cca checkenv' and the result is:
cca v0.4.3
Android Development: SDK configured properly.

so that doesn't seem to be the problem

**Comment by felquis** [comment]
@Megalepozy What OS are you using? Linux/Windows/OSX?

**Comment by megalepozy** [comment]
@felquis Fedora 20

**Comment by felquis** [comment]
@Megalepozy One of my friends using Ubuntu couldn't run CCA too. His problem was that a JAVA_HOME variable was not defined, and CCA fails silently.

Can you confirm that you have all variable setup correctly?

**Comment by megalepozy** [comment]
@felquis yup the JAVA_HOME variable was set (actually I think that without setting this env variable I couldn't even install the SDK but I'm not sure)

**Comment by fer-ri** [comment]
I've got some error too, i'm using win7 32 bit

```
$ cca platform add android
cca v0.5.0
Creating android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: com.your.company.projectname
        Name: projectname
        Android target: android-19
Copying template files...
Project successfully created.
Running command: d:\nodejs\node.exe d:\wamp\www\ionic-cca\hooks\before_prepare\cca-pre-prepare.js d:/wamp/www/ionic-cca

d:\nodejs\node_modules\cca\node_modules\q\q.js:128
                    throw e;
                          ^
TypeError: Cannot read property 'cordova' of undefined
    at prePrepareCommand (d:\nodejs\node_modules\cca\src\pre-prepare.js:41:33)
    at commandActions.pre-prepare (d:\nodejs\node_modules\cca\src\cca.js:114:38)
    at _fulfilled (d:\nodejs\node_modules\cca\node_modules\q\q.js:794:54)
    at self.promiseDispatch.done (d:\nodejs\node_modules\cca\node_modules\q\q.js:823:30)
    at Promise.promise.promiseDispatch (d:\nodejs\node_modules\cca\node_modules\q\q.js:756:13)
    at d:\nodejs\node_modules\cca\node_modules\q\q.js:564:44
    at flush (d:\nodejs\node_modules\cca\node_modules\q\q.js:110:17)
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
Error: Hook failed with error code 8: d:\wamp\www\ionic-cca\hooks\before_prepare\cca-pre-prepare.js
    at d:\nodejs\node_modules\cca\node_modules\cordova\node_modules\cordova-lib\src\hooks\HooksRunner.js:194:23
    at _rejected (d:\nodejs\node_modules\cca\node_modules\cordova\node_modules\q\q.js:797:24)
    at d:\nodejs\node_modules\cca\node_modules\cordova\node_modules\q\q.js:823:30
    at Promise.when (d:\nodejs\node_modules\cca\node_modules\cordova\node_modules\q\q.js:1035:31)
    at Promise.promise.promiseDispatch (d:\nodejs\node_modules\cca\node_modules\cordova\node_modules\q\q.js:741:41)
    at d:\nodejs\node_modules\cca\node_modules\cordova\node_modules\q\q.js:557:44
    at flush (d:\nodejs\node_modules\cca\node_modules\cordova\node_modules\q\q.js:108:17)
    at process._tickCallback (node.js:415:13)
```

Any idea? Thanks :)

**Comment by felquis** [comment]
Funny fact .. Yesterday I installed CCA from git, and I got a similar
error...

I'll make some tests today and try to help you.
Em 03/12/2014 11:58, "ghprod" notifications@github.com escreveu:

**Comment by fer-ri** [comment]
Thanks alot @Felquis for your help :)

Regards

**Comment by felquis** [comment]
@ghprod can you clone this repo again, check the steps listed in the README and tell me if the error still   happening. Thanks :)

**Comment by felquis** [comment]
@Megalepozy you are getting the same error using CCA 0.5.0?

**Comment by megalepozy** [comment]
@felquis Didn't try version 0.5.0 (wasn't out then I think), for the time being I'm not even working with cca.... can't waste more time on it... will try it again in about 2 months probably

**Comment by felquis** [comment]
Okay, thanks @Megalepozy

**Comment by fer-ri** [comment]
Great .. thanks a lot, its work now :D

![image](https://cloud.githubusercontent.com/assets/1922652/5333483/2193c48a-7eab-11e4-8c1f-651a5d4cc854.png)

But the size is over 66MB, and why i dont see any huge improved perfomance over standard ionic ? do you feel the same?

Thanks @felquis :)

**Comment by felquis** [comment]
Shouldn't be 66mb, but something more than 17mb.

I'm not sure if you already read this [Crosswalk advantages and tradeoffs](https://github.com/MobileChromeApps/mobile-chrome-apps/blob/master/docs/Crosswalk.md).

2014-12-07 22:24 GMT-02:00 ghprod notifications@github.com:

> Great .. thanks a lot, its work now :D
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/1922652/5333483/2193c48a-7eab-11e4-8c1f-651a5d4cc854.png
> 
> But the size is over 66MB, and why i dont see any huge improved perfomance
> over standard ionic ? do you feel the same?
> 
> Thanks @felquis https://github.com/felquis :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/felquis/ionic-cca/issues/1#issuecomment-65963240.

## 

Felquis Gimenes - Front-end
felquis.com +55 011 95980 2233

**Comment by fer-ri** [comment]
Ah yes, i read that few days ago and simply forgot bout that :)

And i dont know why size is too huge.. strange .. 

anyway Thanks :)
